class AppStrings {
    static String appname = "MediCare",
    bestDocapp = "Best Doctor\n Appointment App",
    welcomeBack = "Welcome Back!",
    weAreExcited = "We're excited to have you back!",
    signupNow = "Sign up now and start exploring all that our app has to offer.",
    email = "Email",
    emailHint = "Enter your email",
    password = "Password",
    passwordHint = "Enter your password ",
    fullname = "Full Name",
    fullnameHint = "Enter your name here...",
    confirmPassword = "Confirm Password",
    forgetPassword = "Forget Password?",
    login = "Login",
    category = "Category",
    doctor = "Doctor",
    settings = "Settings",
    search = "Search Doctor",
    signup = "Signup",
    alreadyHaveAccount = "Account have an account?",
    dontHaveAccount = "Don't have an account?",
    welcome = "Let's Find your Specialist",
    body = "Body",
    ear = "Ear",
    liver = "Liver",
    lungs = "Lungs",
    heart = "Heart",
    kidney = "Kidney",
    eye = "Eye",
    stomach = "Stomach",
    tooth = "Tooth",
    changePassword = "Change Password",
    termsConditions = "Terms & Conditions",
    signout = "Signout";

}
