// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDgtS2U7LKCkWydwa4tbmAl-ndsf2Kxms',
    appId: '1:873393942099:web:491f22c99b285414ffa0a6',
    messagingSenderId: '873393942099',
    projectId: 'medicare-b1a4a',
    authDomain: 'medicare-b1a4a.firebaseapp.com',
    storageBucket: 'medicare-b1a4a.appspot.com',
    measurementId: 'G-NV5GV8QRST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR9wwxIeqzsKZub6-dG_clyGOSAzZPDY8',
    appId: '1:873393942099:android:b2231a10ee795896ffa0a6',
    messagingSenderId: '873393942099',
    projectId: 'medicare-b1a4a',
    storageBucket: 'medicare-b1a4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5mkh4vkIViPDVfuUNPm7ID_ZgNTWU5Zc',
    appId: '1:873393942099:ios:0479a894ea2322faffa0a6',
    messagingSenderId: '873393942099',
    projectId: 'medicare-b1a4a',
    storageBucket: 'medicare-b1a4a.appspot.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5mkh4vkIViPDVfuUNPm7ID_ZgNTWU5Zc',
    appId: '1:873393942099:ios:0479a894ea2322faffa0a6',
    messagingSenderId: '873393942099',
    projectId: 'medicare-b1a4a',
    storageBucket: 'medicare-b1a4a.appspot.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDgtS2U7LKCkWydwa4tbmAl-ndsf2Kxms',
    appId: '1:873393942099:web:99046acacaf5b1b1ffa0a6',
    messagingSenderId: '873393942099',
    projectId: 'medicare-b1a4a',
    authDomain: 'medicare-b1a4a.firebaseapp.com',
    storageBucket: 'medicare-b1a4a.appspot.com',
    measurementId: 'G-0GC786W3NW',
  );
}
